--- 
- hosts: localhost
  tasks:
  - name: Creamos nuestro servidor
    ec2:
      region: sa-east-1
      instance_type: t2.micro
      image: ami-054a31f1b3bf90920
      keypair: digitalhouse
      wait: yes
      wait_timeout: 500
      volumes:
        - device_name: /dev/xvda
          volume_type: gp2
          volume_size: 8
      vpc_subnet_id: subnet-0327eec92a1bb1143
      assign_public_ip: yes